c_ssrs_intake = [
    'c_ssrs_1_life',
    'c_ssrs_2_life',
    'c_ssrs_3_life',
    'c_ssrs_4_life',
    'c_ssrs_5_life',
    'c_ssrs_6_life',
    'c_ssrs_1_2weeks',
    'c_ssrs_2_2weeks',
    'c_ssrs_3_2weeks',
    'c_ssrs_4_2weeks',
    'c_ssrs_5_2weeks',
    'c_ssrs_6_2weeks',
    'c_ssrs_6_3month',
    'c_ssrs_7_intake',
    'c_ssrs_8_intake'
]


c_ssrs = [
    'c_ssrs_1',
    'c_ssrs_2',
    'c_ssrs_3', 
    'c_ssrs_4', 
    'c_ssrs_5',
    'c_ssrs_6',
    'c_ssrs_last_visit_6',
    'c_ssrs_7',
    'c_ssrs_8',
]

mfq = [
 'mfq_1',
 'mfq_2',
 'mfq_5',
 'mfq_7',
 'mfq_8',
 'mfq_14',
 'mfq_21',
 'mfq_23',
 'mfq_24',
 'mfq_27',
 'mfq_28',
 'mfq_30',
 'mfq_31',
 'mfq_34',
 'mfq_35',
 'mfq_36',
 'mfq_37'
]

siq = [
 'siq_1',
 'siq_2',
 'siq_3',
 'siq_4',
 'siq_5',
 'siq_6',
 'siq_7',
 'siq_8',
 'siq_9',
 'siq_10',
 'siq_11',
 'siq_12',
 'siq_13',
 'siq_14',
 'siq_15'
]


sdq = [
     'sdq_1',
     'sdq_2',
     'sdq_3',
     'sdq_4',
     'sdq_5',
     'sdq_6',
     'sdq_7',
     'sdq_8',
     'sdq_9',
     'sdq_10',
     'sdq_11',
     'sdq_12',
     'sdq_13',
     'sdq_14',
     'sdq_15',
     'sdq_16',
     'sdq_17',
     'sdq_18',
     'sdq_19',
     'sdq_20',
     'sdq_21',
     'sdq_22',
     'sdq_23',
     'sdq_24',
     'sdq_25'
]

scared = [    
    'scared_1',
    'scared_2',
    'scared_3',
    'scared_4',
    'scared_5',
    'scared_6',
    'scared_7',
    'scared_8',
    'scared_9',
    'scared_10',
    'scared_11',
    'scared_12',
    'scared_13',
    'scared_14',
    'scared_15',
    'scared_16',
    'scared_17',
    'scared_18',
    'scared_19',
    'scared_20',
    'scared_21',
    'scared_22',
    'scared_23',
    'scared_24',
    'scared_25',
    'scared_26',
    'scared_27',
    'scared_28',
    'scared_29',
    'scared_30',
    'scared_31',
    'scared_32',
    'scared_33',
    'scared_34',
    'scared_35',
    'scared_36',
    'scared_37',
    'scared_38',
    'scared_39',
    'scared_40',
    'scared_41' 
]


ATHENS = [
    'athens_1',
    'athens_2',
    'athens_3',
    'athens_4',
    'athens_5',
    'athens_6',
    'athens_7',
    'athens_8'
]

SAS = [
    'sas_1',
    'sas_2',
    'sas_3',
    'sas_4',
    'sas_5',
    'sas_6',
    'sas_7',
    'sas_8',
    'sas_9',
    'sas_10',
    'sas_11',
    'sas_12',
    'sas_13',
    'sas_14',
    'sas_15',
    'sas_16',
    'sas_17',
    'sas_18',
    'sas_19',
    'sas_20',
    'sas_21',
    'sas_22',
    'sas_23'
]


sci_af_ca= [
    'sci_af_ca_1',
    'sci_af_ca_2',
    'sci_af_ca_3',
    'sci_af_ca_4',
    'sci_af_ca_5',
    'sci_af_ca_6',
    'sci_af_ca_7',
    'sci_af_ca_8',
    'sci_af_ca_9',
    'sci_af_ca_10',
    'sci_af_ca_11',
    'sci_af_ca_12',
    'sci_af_ca_13',
    'sci_af_ca_14',
    'sci_af_ca_15',
    'sci_af_ca_16',
    'sci_af_ca_17',
    'sci_af_ca_18',
    'sci_af_ca_19',
    'sci_af_ca_20',
    'sci_af_ca_21',
    'sci_af_ca_22',
    'sci_af_ca_23',
    'sci_af_ca_24',
    'sci_af_ca_25',
    'sci_af_ca_26',
    'sci_af_ca_27',
    'sci_af_ca_28',
    'sci_af_ca_29',
    'sci_af_ca_30',
    'sci_af_ca_31',
    'sci_af_ca_32',
    'sci_af_ca_33',
    'sci_af_ca_34',
    'sci_af_ca_35',
    'sci_af_ca_36',
    'sci_af_ca_37',
    'sci_af_ca_38',
    'sci_af_ca_39',
    'sci_af_ca_40'
]

scs_clin = [
    'sci_c_1_1_clin',
    'scs_2_1_clin',
    'scs_2_2_clin',
    'scs_2_3_clin',
    'scs_2_4_clin',
    'sci_c_3_1_clin',
    'sci_c_3_2_clin',
    'sci_c_3_3_clin',
    'sci_c_3_4_clin',
    'sci_c_4_1_clin',
    'sci_c_4_2_clin',
    'sci_c_4_3_clin',
    'sci_c_4_4_clin',
    'sci_c_5_1_clin',
    'sci_c_5_2_clin'
]


scs_stu = [
    'sci_c_1_1_stu',
    'scs_2_1_stu',
    'scs_2_2_stu',
    'scs_2_3_stu',
    'scs_2_4_stu',
    'sci_c_3_1_stu',
    'sci_c_3_2_stu',
    'sci_c_3_3_stu',
    'sci_c_3_4_stu',
    'sci_c_4_1_stu',
    'sci_c_4_2_stu',
    'sci_c_4_3_stu',
    'sci_c_4_4_stu',
    'sci_c_5_1_stu',
    'sci_c_5_2_stu'
]

sci_mother = [
    'sci_p_1_m',
    'sci_p_2_m',
    'sci_p_3_m',
    'sci_p_4_m',
    'sci_p_5_m',
    'sci_p_6_m',
    'sci_p_7_m',
    'sci_p_8_m',
    'sci_p_9_m',
    'sci_p_10_m',
    'sci_p_11_m',
    'sci_p_12_m',
    'sci_p_13_m',
    'sci_p_14_m',
    'sci_p_15_m'
]

sci_father = [
    'sci_p_1_f',
    'sci_p_2_f',
    'sci_p_3_f',
    'sci_p_4_f',
    'sci_p_5_f',
    'sci_p_6_f',
    'sci_p_7_f',
    'sci_p_8_f',
    'sci_p_9_f',
    'sci_p_10_f',
    'sci_p_11_f',
    'sci_p_12_f',
    'sci_p_13_f',
    'sci_p_14_f',
    'sci_p_15_f'
]